rule("copy_assets")
    after_build(function(target)
        os.cp("$(projectdir)/Assets", target:targetdir())
    end)
rule_end()

includes("TickOneFrame")
includes("Application")
includes("LifeTimeComponents")
includes("NativeScripting")
includes("InputSystem")
includes("AudioSystem")
includes("PhysicsSystem")